apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      containers:
        - name: testdeploy
          image: 10.2.0.63/cpatil/cpatil
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: testdeploy
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: testdeploy
